import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/beer/assets/navbar'
import Footer from '@/app/footer/page'
import Navigation from '@/components/beer/assets/navigation'
import Chevron from '@/app/chevron/page'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className='w-full h-full'>
					<header>
						<Navbar />
					</header>
					<main>{children}</main>
					<footer>
						<Chevron />
						<Navigation />
						<Footer />
					</footer>
				</div>
			</body>
		</html>
	)
}
